Repository Team-Packman/Packman-Server, pull requests merged in 2022-07, with the labels that each got.

#7 [FEAT] 유저 프로필 수정
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/AuthController.ts
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/index.ts
  src/interface/IUserInfo.ts
  src/interface/common/JWTPayloadInfo.ts
  src/interface/user/UserInfo.ts
  src/middleware/auth.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/AuthService.ts
  src/services/UserService.ts
  src/services/index.ts
  yarn.lock
Labels: Enhancement⭐, 경린🐹, PATCH✂️

#13 [FEAT] 혼자 패킹리스트 생성
  package.json
  src/controllers/AlonePackingListController.ts
  src/controllers/index.ts
  src/index.ts
  src/interface/IAlonePackingList.ts
  src/loaders/db.ts
  src/models/AlonePackingList.ts
  src/models/Category.ts
  src/models/Group.ts
  src/models/Pack.ts
  src/models/Template.ts
  src/models/TogetherPackingList.ts
  src/modules/responseMessage.ts
  src/routes/PackingListRouter.ts
  src/routes/index.ts
  src/services/AlonePackingListService.ts
  src/services/index.ts
  yarn.lock
Labels: Enhancement⭐, 서희🥑, POST📦

#14 [FEAT] 함께 패킹리스트 카테고리 생성
  src/controllers/TogetherPackingListCategoryController.ts
  src/controllers/index.ts
  src/interface/IAlonePackingList.ts
  src/interface/ICategory.ts
  src/interface/IFolder.ts
  src/interface/IGroup.ts
  src/interface/IPack.ts
  src/interface/ITemplate.ts
  src/interface/ITogetherPackingList.ts
  src/interface/ITogetherPackingListInfo.ts
  src/interface/IUser.ts
  src/interface/IUserInfo.ts
  src/loaders/db.ts
  src/models/AlonePackingList.ts
  src/models/Category.ts
  src/models/Folder.ts
  src/models/Group.ts
  src/models/Pack.ts
  src/models/Template.ts
  src/models/TogetherPackingList.ts
  src/models/User.ts
  src/modules/responseMessage.ts
  src/routes/TogetherPackingListCategoryRouter.ts
  src/routes/index.ts
  src/services/TogetherPackingListCategoryService.ts
  src/services/index.ts
Labels: Enhancement⭐, 현지👻, POST📦

#9 [FEAT] 폴더 생성
  src/controllers/FolderController.ts
  src/interface/IFolder.ts
  src/modules/folderResponse.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/routes/index.ts
  src/services/FolderService.ts
  src/services/index.ts
Labels: Enhancement⭐, 경린🐹, POST📦

#18 [FEAT] 함께 패킹리스트 카테고리 수정
  src/controllers/AuthController.ts
  src/controllers/TogetherPackingListCategoryController.ts
  src/interface/ICategory.ts
  src/modules/responseMessage.ts
  src/routes/TogetherPackingListCategoryRouter.ts
  src/services/AuthService.ts
  src/services/TogetherPackingListCategoryService.ts
Labels: Enhancement⭐, 현지👻, PATCH✂️

#19 [CHORE] 혼자 패킹리스트 생성 count 기능 추가
  src/controllers/AlonePackingListController.ts
  src/models/AlonePackingList.ts
  src/routes/index.ts
  src/services/AlonePackingListService.ts
Labels: 서희🥑, POST📦

#20 [FEAT] 함께 패킹리스트 생성 구현
  src/controllers/TogetherPackingListController.ts
  src/controllers/index.ts
  src/interface/ITogetherPackingList.ts
  src/models/Group.ts
  src/models/TogetherPackingList.ts
  src/modules/responseMessage.ts
  src/routes/PackingListRouter.ts
  src/routes/TogetherPackingListCategoryRouter.ts
  src/routes/index.ts
  src/services/TogetherPackingListService.ts
  src/services/index.ts
Labels: Enhancement⭐, 서희🥑, POST📦

#24 [FEAT]/#22 함께 패킹리스트 카테고리 삭제 구현
  src/controllers/TogetherPackingListCategoryController.ts
  src/interface/ICategory.ts
  src/modules/responseMessage.ts
  src/routes/TogetherPackingListCategoryRouter.ts
  src/services/TogetherPackingListCategoryService.ts
Labels: Enhancement⭐, 현지👻, DELETE💥

#16 [FEAT] 폴더 삭제
  src/controllers/FolderController.ts
  src/controllers/index.ts
  src/routes/AuthRouter.ts
  src/routes/FolderRouter.ts
  src/routes/index.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, 경린🐹, DELETE💥

#25 [FEAT]/#17 폴더 수정
  src/controllers/FolderController.ts
  src/interface/IFolder.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, 경린🐹, PATCH✂️

#29 [FEAT] 폴더 조회
  src/controllers/FolderController.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, 경린🐹, GET🔮

#31 [FEAT] 패킹리스트 제목 수정 구현
  src/controllers/PackingListController.ts
  src/controllers/index.ts
  src/interface/IPackingList.ts
  src/modules/responseMessage.ts
  src/routes/PackingListRouter.ts
  src/services/PackingListService.ts
  src/services/TogetherPackingListService.ts
  src/services/index.ts
Labels: Enhancement⭐, 서희🥑, PATCH✂️

#32 [FEAT] 함께 패킹리스트 짐 생성
  src/controllers/TogetherPackingListPackController.ts
  src/controllers/index.ts
  src/interface/ITogetherPackingList.ts
  src/modules/responseMessage.ts
  src/routes/TogetherPackingListPackRouter.ts
  src/routes/index.ts
  src/services/TogetherPackingListPackService.ts
  src/services/index.ts
Labels: Enhancement⭐, 현지👻, POST📦

#41 [CHORE] packingList together, alone 라우팅 변경
  src/routes/AlonePackingListRouter.ts
  src/routes/PackingListRouter.ts
  src/routes/TogetherPackingListRouter.ts
  src/routes/index.ts
Labels: 서희🥑

#44 [FEAT] 함께 패킹리스트 짐 수정
  src/controllers/TogetherPackingListCategoryController.ts
  src/controllers/TogetherPackingListPackController.ts
  src/interface/IPack.ts
  src/modules/responseMessage.ts
  src/routes/TogetherPackingListPackRouter.ts
  src/services/TogetherPackingListCategoryService.ts
  src/services/TogetherPackingListPackService.ts
Labels: Enhancement⭐, 현지👻, PATCH✂️

#48 [FEAT] 패킹 리스트 생성 시 폴더 조회
  src/controllers/FolderController.ts
  src/controllers/UserController.ts
  src/interface/IFolder.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/routes/index.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, 경린🐹, GET🔮

#50 [FEAT]/#45 함께 패킹리스트 짐 삭제 구현
  src/controllers/TogetherPackingListPackController.ts
  src/routes/TogetherPackingListPackRouter.ts
  src/services/TogetherPackingListCategoryService.ts
  src/services/TogetherPackingListPackService.ts
Labels: Enhancement⭐, 현지👻, DELETE💥

#53 [FEAT] 함께 패킹 리스트 템플릿 조회 구현
  src/controllers/TemplateController.ts
  src/modules/responseMessage.ts
  src/routes/TemplateRouter.ts
  src/services/TemplateService.ts
Labels: Enhancement⭐, 서희🥑, GET🔮

#56 [FEAT] 템플릿 상세 조회 구현
  src/controllers/TemplateController.ts
  src/interface/ITemplate.ts
  src/modules/responseMessage.ts
  src/routes/TemplateRouter.ts
  src/services/TemplateService.ts
Labels: Enhancement⭐, 서희🥑, GET🔮

#57 [FEAT]/#55 함께 패킹리스트 담당자 배정 구현
  src/controllers/TogetherPackingListController.ts
  src/interface/IPack.ts
  src/modules/responseMessage.ts
  src/routes/TogetherPackingListRouter.ts
  src/services/TogetherPackingListService.ts
Labels: Enhancement⭐, 현지👻, PATCH✂️

#59 [FIX] Date->string 수정
  package.json
  src/controllers/TogetherPackingListCategoryController.ts
  src/interface/IAlonePackingList.ts
  src/interface/IPackingList.ts
  src/interface/ITogetherPackingList.ts
  src/models/AlonePackingList.ts
  src/models/TogetherPackingList.ts
  src/services/TogetherPackingListService.ts
  yarn.lock
Labels: 서희🥑, POST📦, PATCH✂️

#69 [FEAT] 혼자패킹리스트 상세조회 구현
  src/controllers/AlonePackingListController.ts
  src/modules/aloneListResponse.ts
  src/modules/responseMessage.ts
  src/modules/togetherListResponse.ts
  src/routes/AlonePackingListRouter.ts
  src/services/AlonePackingListService.ts
  src/services/TogetherPackingListService.ts
Labels: Enhancement⭐, 서희🥑, GET🔮

#71 [CHORE] 함께 패킹리스트 카테고리/짐 수정에서 id를 _id로 수정
  src/interface/ICategory.ts
  src/interface/IPack.ts
  src/routes/TogetherPackingListCategoryRouter.ts
  src/routes/TogetherPackingListPackRouter.ts
  src/services/AuthService.ts
  src/services/TogetherPackingListCategoryService.ts
  src/services/TogetherPackingListPackService.ts
Labels: 현지👻

#72 [FEAT] 폴더 안 함께 패킹리스트 조회 구현
  src/controllers/FolderController.ts
  src/interface/IFolder.ts
  src/interface/ITogetherPackingList.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
  src/services/TogetherPackingListService.ts
Labels: Enhancement⭐, 현지👻, GET🔮

#74 [FEAT]/#70 폴더 속 혼자 패킹리스트 구현
  src/controllers/AlonePackingListController.ts
  src/modules/responseMessage.ts
  src/routes/AlonePackingListRouter.ts
  src/services/AlonePackingListService.ts
Labels: Enhancement⭐, 서희🥑, DELETE💥

#78 [FEAT] 함께 패킹에 group response 추가
  src/controllers/TogetherPackingListController.ts
  src/services/MemberService.ts
  src/services/TogetherPackingListService.ts
Labels: 경린🐹, GET🔮, Fix🪄

#67 [FEAT] 혼자 패킹 리스트 생성 & 수정
  src/controllers/AlonePackingListCategoryController.ts
  src/interface/IAlonePackingList.ts
  src/modules/responseMessage.ts
  src/routes/AlonePackingListCategoryRouter.ts
  src/routes/index.ts
  src/services/AlonePackingListCategoryService.ts
Labels: Enhancement⭐, 경린🐹, PATCH✂️

#81 [FEAT] 폴더 속 혼자 패킹리스트들 조회 구현
  src/services/FolderService.ts
Labels: Enhancement⭐, 서희🥑, GET🔮

#82 [FEAT] 함께 패킹리스트 그룹 생성시 본인 추가 구현
  src/controllers/TogetherPackingListController.ts
  src/services/TogetherPackingListService.ts
Labels: 서희🥑, GET🔮

#84 [FEAT]/#80 함께 패킹 리스트 카테고리삭제
  src/controllers/AlonePackingListCategoryController.ts
  src/routes/AlonePackingListCategoryRouter.ts
  src/services/AlonePackingListCategoryService.ts
Labels: Enhancement⭐, 경린🐹, DELETE💥

#86 [FEAT]/#83 혼자 패킹리스트 짐 생성 구현
  src/controllers/AlonePackingListPackController.ts
  src/routes/AlonePackingListPackRouter.ts
  src/routes/index.ts
  src/services/AlonePackingListPackService.ts
Labels: Enhancement⭐, 서희🥑, GET🔮

#88 [FEAT] 혼자 패킹 리스트 짐 수정
  src/controllers/AlonePackingListPackController.ts
  src/controllers/TogetherPackingListPackController.ts
  src/routes/AlonePackingListPackRouter.ts
  src/services/AlonePackingListPackService.ts
Labels: Enhancement⭐, 경린🐹, PATCH✂️

#89 [FEAT] 혼자 패킹리스트 삭제 구현
  src/controllers/AlonePackingListPackController.ts
  src/routes/AlonePackingListPackRouter.ts
  src/services/AlonePackingListPackService.ts
Labels: Enhancement⭐, 서희🥑, DELETE💥

#90 [FEAT]/#73 최근 생성된 리스트 조회 구현
  src/controllers/FolderController.ts
  src/interface/IAlonePackingList.ts
  src/interface/IPackingList.ts
  src/interface/ITogetherPackingList.ts
  src/modules/responseMessage.ts
  src/routes/FolderRouter.ts
  src/services/FolderService.ts
Labels: Enhancement⭐, 현지👻, GET🔮

#92 [ADD]/#91 user 구글 로그인 시 isDeleted 처리
  src/services/AuthService.ts
Labels: 경린🐹, Fix🪄
